@startuml
'https://plantuml.com/class-diagram

!includesub ..\imodechangesubscriber.puml!IModeChangeSubscriberSub
!includesub ..\program\iprogramchangesubscriber.puml!IProgramChangeSubscriberSub

!startsub LedsSub

class Leds
{

}

!endsub

Leds -up-|> IProgramChangeSubscriber
Leds -up-|> IModeChangeSubscriber
@enduml