@startuml
'https://plantuml.com/class-diagram

!startsub IProgramChangeSubscriberSub

interface IProgramChangeSubscriber
{
    {abstract} void OnProgramChange(tProgramIndex index)
}

!endsub

note left of IProgramChangeSubscriber
  Отвечает за оповещение
  о смене программы, а также
  о том, что программа поменялась на
  ОС, ЖЖ или КК
end note


@enduml