@startuml
'https://plantuml.com/class-diagram


!startsub IProgramConfigurationStorageSub

class IProgramConfigurationStorage
{
    {abstract} ReturnCode Set(const ProgramConfiguration& programConfiguration)
    {abstract} ReturnCode Get(ProgramConfiguration& programConfiguration)
}
!endsub

note left of IProgramConfigurationStorage
  Отвечает за хранение
  и установку конфигурации программ
end note
@enduml