@startuml
'https://plantuml.com/class-diagram

!includesub iprogramconfigurationstorage.puml!IProgramConfigurationStorageSub
!startsub ProgramConfigurationStorageSub

class ProgramConfigurationStorage
{
    +ReturnCode Set(const ProgramConfiguration& programConfiguration)
    +ReturnCode Get(ProgramConfiguration& programConfiguration)

    -NvParam<ProgramConfiguration> mProgramConfiguration
}



ProgramConfigurationStorage-up-|>IProgramConfigurationStorage

!endsub

@enduml