:stem:
:figure-caption: Рисунок
:table-caption: Таблица
:sectnums:
:sectnumlevels: 3
:toc-title: Содержание

:toc:



= Требования

Дорожный контроллер SLTraffic (далее ДК) предназначен для управления силовыми модулями, к которым подключаются непосредственно нагрузки в виде светофорных секций, по заданным режимам и программам, для обеспечения функционирования светофорного объекта (далее СО).

Дополнительно ДК имеет интерфейс Ethernet для обеспечения удалённого мониторинга и управления со стороны АСУДД (автоматизированной системы управления дорожным движением) или ЦОДД (центра организации дорожного движения).



== Общие требования и общая архитектура

Предложение использовать RTOS с вытесняющей многозадачностью. Все периодические действия должны быть организованы в виде задач (активных классов).

Общие активные классы и их приоритеты:

[plantuml,format=png]
....
include::common/activetask/activeclasses.puml[]
....

=== Ограничения

==== ПО должно быть написано на языке С++.

=== Функциональные требования
Встроенное ПО должно обеспечивать перечисленный выше и сопутствующий функционал, а именно:

==== Обмен информацией каждый такт (полсекунды) с силовыми модулями (с защитного силового модуля получается информация о напряжении сети, а с остальных о напряжениях и мощностях нагрузок по каналам)

[plantuml,format=png]
....
include::common/activetask/diagnosticservice.puml[]
....

При определении любой из проблем, оповещает подписчиков о возникновении ошибки, через интерфейс IDiagnosticSubscriber (OnAnyError). Подписчиком будет ProgramManager, который отвечает за переключение и исполнение программы.
В случае, если все хорошо, оповещает подписчиков о том, что все хорошо (позволяет покрыть требование *выход из режима ЖМ по устранению причины*)

[plantuml,format=png]
....
include::common/program/programmanager.puml[]
....

==== Передача информации каждый такт на сервер и/или в конфигуратор (при наличии соединения) (сервер, как правило, является TCP-сервером, а конфигуратор – TCP-клиентом) и получение команд от них

[plantuml,format=png]
....
include::common/activetask/serverinterationservice.puml[]
....


==== Обработка кнопок включения режимов ОС (отключения светофора), ЖМ (жёлтого мигания), КК (кругом красных) и отображение режимов работы с помощью светодиодов

[plantuml,format=png]
....
include::common/activetask/buttonservice.puml[]
....

ButtonManager собственно и будет заниматься опросом кнопок и оповещением всех заинтересованных о нажатии на кнопки

[plantuml,format=png]
....
include::common/button/buttonmanager.puml[]
....

Подписчиком ButtonManager будет ProgramManager. По событиям он будет
переключать режим, и как только переключит режим, оповестит контроллер светодиодов
через тот же интерфейс.

[plantuml,format=png]
....
include::common/leds/ledscontroller.puml[]
....

==== Работа по программе (каждый такт определяется текущее состояние каждого направления по программе и в соответствии с таблицами распределения каналов модулей по направлениям и цветам прописывается соответствующее состояние по каждому каналу)

[plantuml,format=png]
....
include::common/activetask/programservice.puml[]
....

==== Управление обратным отсчётом светофоров по дополнительному интерфейсу RS-485, по протоколу «СПЕКТР» версии 2 (ЗАО «РИПАС») (принимаем, что номер группы ТООВ (табло обратного отсчёта времени) по протоколу – это номер направления),

[plantuml,format=png]
....
include::common/activetask/countdowndisplayservice.puml[]
....
