@startuml
'https://plantuml.com/class-diagram

!startsub IDiagnosticSub

interface IDiagnostic
{
    {abstract}bool HasAnyError()
}

!endsub
note left of IDiagnostic
  Отвечает за определение аварийных условий
  конфликт направлений по зелёным сигналам,
  одновременное включение красного и зелёного
  сигналов по одному направлению,
  снижение мощности нагрузки на канале ниже
  минимальной, перегрузка по току,
  наличие напряжения на выключенном канале
  и отсутствие напряжения на включенном
end note

@enduml