@startuml
'https://plantuml.com/class-diagram

!startsub IProgramManagerSub

!includesub iprogram.puml!IProgramSub

interface IProgramManager
{
    {abstract} void ChooseProgram()
    {abstract} void NextTact()
}

IProgramManager ...> IProgram : return

!endsub

@enduml