@startuml
'https://plantuml.com/class-diagram

!includesub ibuttonmanager.puml!IButtonManagerSub
!includesub ..\imodechangesubscriber.puml!IModeChangeSubscriberSub

!startsub ButtonManagerSub

class ButtonManager<auto& ...subscribers>
{
    -array<IModeChangeSubscriber*, sizeof...subscribers> mButtonSubscribers
}
!endsub

ButtonManager -up-|> IButtonManager
ButtonManager o-- IModeChangeSubscriber

note top of ButtonManager
  Отвечает за определение
  об нажатии копок на
  включения режимов и оповещение
  подписчиков через интерфейс
  IModeChangeSubscriber
end note

@enduml